-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgz7LBXHvBbZQaNV5z
Vl6QAhKyVXjD5CdmNDkP/pBc4C+gCgYIKoZIzj0DAQehRANCAAQ+JyTRDFKjXxXg
fnhZnccdVRZK9dWKbEQsK6Ze/09Z1K9i+CuHIn6S03fhBPcmda2xU+ZgLlgJaAbZ
WQros6ML
-----END PRIVATE KEY-----